apiVersion: apps/v1
kind: Deployment
metadata:
  name: server3
  labels:
    app: server3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server3
  template:
    metadata:
      labels:
        app: server3
    spec:
      containers:
      - name: server3
        image: omkar0707/onestop_be1:v1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysqldb3-service:3306/onestop
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: "1234"
        - name: SERVER_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: server3
spec:
  selector:
    app: server3
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: server3-route
spec:
  to:
    kind: Service
    name: server3
  port:
    targetPort: http
  tls:
    termination: edge
